"""
processing/gcs_auth.py
======================
Shared GCS authentication helper for all Spark jobs.

Authentication Strategy (priority order):
  1. SERVICE ACCOUNT KEY (Production / CI-CD / Teammates):
     Set GOOGLE_APPLICATION_CREDENTIALS to a Service Account JSON key file.
     File must be a proper SA key (contains "type": "service_account").

  2. APPLICATION DEFAULT CREDENTIALS - ADC (Local Dev):
     Set GOOGLE_APPLICATION_CREDENTIALS to the ADC file generated by:
       gcloud auth application-default login
     This file contains "type": "authorized_user".

The helper auto-detects which type is present and applies the correct
GCS Connector (hadoop3) configuration. This means teammates only need to
set ONE environment variable regardless of which auth method they use.

Usage:
    from gcs_auth import apply_gcs_auth

    builder = SparkSession.builder.appName("MyJob")
    builder = apply_gcs_auth(builder)
    spark   = builder.getOrCreate()
"""

import json
import logging
import os

log = logging.getLogger("gcs_auth")

# Standard path inside Docker containers (mounted via docker-compose volume)
_DEFAULT_KEY_PATH = "/home/spark/.config/gcloud/application_default_credentials.json"


def _detect_credential_type(key_path: str) -> str:
    """
    Read the JSON key file and return its 'type' field.
    Returns 'service_account' or 'authorized_user' (ADC).
    """
    try:
        with open(key_path, "r") as f:
            cred = json.load(f)
        return cred.get("type", "unknown")
    except Exception as e:
        log.warning("Could not read credential file at %s: %s", key_path, e)
        return "unknown"


def apply_gcs_auth(builder, key_path: str | None = None):
    """
    Apply the correct GCS authentication configuration to a SparkSession builder.

    Args:
        builder:  SparkSession.builder instance (pre-configured with appName/master)
        key_path: Optional path to the credential JSON file.
                  Defaults to env var GOOGLE_APPLICATION_CREDENTIALS,
                  then falls back to the standard Docker mount path.

    Returns:
        The same builder with GCS auth configs applied.
    """
    if key_path is None:
        key_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", _DEFAULT_KEY_PATH)

    cred_type = _detect_credential_type(key_path)
    log.info("GCS credential file  : %s", key_path)
    log.info("GCS credential type  : %s", cred_type)

    # ── Common config: GCS filesystem implementation ──────────────────────────
    builder = (
        builder
        .config("spark.hadoop.fs.gs.impl",
                "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
        .config("spark.hadoop.fs.AbstractFileSystem.gs.impl",
                "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
        # Delta Lake GCS log store (required for atomic commits on GCS)
        .config("spark.delta.logStore.gs.impl",
                "io.delta.storage.GCSLogStore")
    )

    if cred_type == "service_account":
        # ── Production path: Service Account JSON Key ─────────────────────────
        log.info("Auth mode: SERVICE_ACCOUNT_JSON_KEYFILE (production)")
        builder = (
            builder
            .config("spark.hadoop.fs.gs.auth.type",
                    "SERVICE_ACCOUNT_JSON_KEYFILE")
            .config("spark.hadoop.fs.gs.auth.service.account.json.keyfile",
                    key_path)
            .config("spark.hadoop.fs.gs.auth.service.account.enable", "true")
        )

    elif cred_type == "authorized_user":
        # ── Local dev path: ADC (gcloud auth application-default login) ───────
        log.info("Auth mode: USER_CREDENTIALS (ADC / local dev)")
        builder = (
            builder
            .config("spark.hadoop.fs.gs.auth.type", "USER_CREDENTIALS")
            .config("spark.hadoop.fs.gs.auth.client.id",
                    _read_field(key_path, "client_id"))
            .config("spark.hadoop.fs.gs.auth.client.secret",
                    _read_field(key_path, "client_secret"))
            .config("spark.hadoop.fs.gs.auth.refresh.token",
                    _read_field(key_path, "refresh_token"))
        )

    else:
        # ── Fallback: Let GCS Connector figure it out via GOOGLE_CLOUD_AUTH ───
        log.warning(
            "Auth mode: UNKNOWN credential type '%s'. "
            "Falling back to APPLICATION_DEFAULT. "
            "This may fail. Set GOOGLE_APPLICATION_CREDENTIALS correctly.",
            cred_type
        )
        builder = builder.config(
            "spark.hadoop.fs.gs.auth.type", "APPLICATION_DEFAULT"
        )

    return builder


def _read_field(key_path: str, field: str) -> str:
    """Read a single field from the credential JSON file."""
    try:
        with open(key_path, "r") as f:
            return json.load(f).get(field, "")
    except Exception:
        return ""
